package Utilities;

public enum TokenType {
    UNKNOWN, MUTABLE_ID_DECL, INT_TYPE, FLOAT_TYPE, ID, INT, FLOAT,
    PLUS, MINUS, ADD, SUB, MULT, DIV,
    LPAREN, RPAREN, COLON, SEMICOLON, DOT, ASSIGNMENT
}
